### PR TITLE
[FEAT] Different dependencies per function

### PR DESCRIPTION
**Pull request by jm-moreau**
Hi Adam, @awtkns 

I needed this feature. :) So, I tried to implement it according to the discussion.

Let me know if you have any feedback.

Best,
JM

### CODE REVIEW

**Comment by awtkns** [comment]
Hey thanks @jm-moreau. Hoping to get a review done for you later today 😄

**Comment by jm-moreau** [comment]
Hey Adam,

Maybe a quick chat would be worthwhile. I am running with fastapi-crudrouter, and had to implement a bunch of things to make it work for my application.  But ideally, I could just PR these instead of using and maintaining my own fork.  I think a 15 min chat would work out better to bounce ideas than only using github.  How does that sound?

**Comment by awtkns** [comment]
Good idea! @jm-moreau Does right now work? You can send me a chat invite (zoom, teams, discord, etc..) to `cadamrun@gmail.com`

**Comment by awtkns** [comment]
Feature moved to PR #60 (Allows for a sequence of dependencies for all CRUDRouter backends).

Still looking at ways to implement the feature we chatted about.

**Pull request closed without merging**
