### PR TITLE
Dependencies can be added to each separate route (list of dependencies)

### PR DESCRIPTION
**Pull request by DorskFR**
Hello,

So as discussed in #37

I think this might be how to make a pull request so I give it a try.

If this is not needed or too late, it's fine, I am glad to learn!

closes #59 #37

### CODE REVIEW

**Comment by awtkns** [comment]
Hi @DorskFR. This looks great! For here all I guess all we would need to do is update the docs to document this feature. 

And maybe write some tests for it (which I can do) 😄

**Review by awtkns — APPROVED** [review]
LGTM! Good to merge once docs are updated.

**Comment by DorskFR** [comment]
Hi @awtkns,

Thank you for your reply!
I see you moved the test to check if its a bool or a dependency to the add_api_route.
It's way better indeed, it avoids many repetitions in every router.

Thanks for the opportunity to create this PR.
I will try to study how you wrote the existing tests next.

**Comment by awtkns** [comment]
@DorskFR Thanks for the PR. The feature is now released with version 0.7.0

**Pull request merged**
